### ISSUE TITLE
Structural change:  add subverse fields on lwc

### ISSUE THREAD

**Issue by krokkie** [refstudycentre/living_word#10]
TODO: lwc add fields:  
    subverse-text varchar(100);  optional - net vir single-verse ranges
    subverse-start-pos integer;  
    subverse-translation-abbr;

**Comment by rudolfbyker** [comment]
Done.
Added field `lw_subverse` of type `living_word_quote` which caches a part of the selected verse. The `translation-abbr` is stored in the `lw_scripture` field already.
