### ISSUE TITLE
Sub-verse widget for lwc's

### ISSUE THREAD

**Issue by krokkie** [refstudycentre/living_word#7]
Create a subverse widget where it takes one verse, and allows you to highlight the relevant part that your comment specifically refers to.  Similar to tablet-text-selector widget.

**Comment by rudolfbyker** [comment]
This blocks Issue #11

**Comment by rudolfbyker** [comment]
Starting with dev-subverse-field. Will make dev-subverse-widget later, as the widget can only be tested if a robust field implementation exists. Learned this the hard way with the scripture module...

**Comment by rudolfbyker** [comment]
Maybe this field type and widget should be a standalone module? We can pass the bible verse (or any text for that matter) to the widget. The field simply stores
- starting character position
- the selected text
  A separate field could store the translation, making the above-mentioned field standalone.
  @krokkie would you agree?

**Comment by krokkie** [comment]
Yip, agree. 
Input == text 
Output = selection, could reduce this to start + len ?
Settings:  single-range-only;   Could later extend this is allow multiple ranges ?
Maybe try "rangy" - see an example here:  http://rangy.googlecode.com/svn/trunk/demos/highlighter.html
https://github.com/timdown/rangy

**Comment by rudolfbyker** [comment]
Done.
TODO: eye-candy. That would be a new issue for a later version.
